/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import BUS.BUS_Device;
import BUS.BUS_Member;
import BUS.BUS_Processing;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Duc Anh
 */
public class Statistics extends javax.swing.JFrame {

    private BUS_Device bd;
    private BUS_Member bm;
    private BUS_Processing bp;
    /**
     * Creates new form Statistics
     */
    public Statistics() {
        initComponents();
        bd = new BUS_Device();
        bm = new BUS_Member();
        bp = new BUS_Processing();
        Render();
        ShowTable1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJoinTime2 = new javax.swing.JLabel();
        joinTimeChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        comboBoxStatistics = new javax.swing.JComboBox<>();
        labelStatisticsFor = new javax.swing.JLabel();
        labelDepartment = new javax.swing.JLabel();
        comboBoxDepartment = new javax.swing.JComboBox<>();
        labelBranch = new javax.swing.JLabel();
        comboBoxBranch = new javax.swing.JComboBox<>();
        labelJoinDate = new javax.swing.JLabel();
        joinDateChooser = new com.toedter.calendar.JDateChooser();
        labelBorrowDate = new javax.swing.JLabel();
        borrowDateChooser = new com.toedter.calendar.JDateChooser();
        labelPayDate = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        comboBoxStatus = new javax.swing.JComboBox<>();
        payDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        labelJoinTime2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        labelJoinTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJoinTime2.setText("Thời gian vào");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 255, 102));

        labelTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 0, 0));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("THỐNG KÊ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(442, 442, 442))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        comboBoxStatistics.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comboBoxStatistics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thiết bị ", "Thành viên ", "Xử lý vi phạm" }));
        comboBoxStatistics.setAlignmentY(1.5F);
        comboBoxStatistics.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxStatisticsItemStateChanged(evt);
            }
        });

        labelStatisticsFor.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        labelStatisticsFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStatisticsFor.setText("Thống kê theo");

        labelDepartment.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        labelDepartment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDepartment.setText("Khoa");

        comboBoxDepartment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        labelBranch.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        labelBranch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBranch.setText("Ngành");

        comboBoxBranch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        labelJoinDate.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        labelJoinDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJoinDate.setText("Thời gian vào");

        labelBorrowDate.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        labelBorrowDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBorrowDate.setText("Thời gian mượn");

        labelPayDate.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        labelPayDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPayDate.setText("Thời gian trả");

        labelStatus.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStatus.setText("Tình trạng xử lý");

        comboBoxStatus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vi phạm", "Chưa vi phạm" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleParent(jPanel1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDepartment)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelBorrowDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrowDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(labelStatisticsFor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelPayDate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(payDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelJoinDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(joinDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStatisticsFor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(joinDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelJoinDate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(borrowDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelBorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(payDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxStatisticsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxStatisticsItemStateChanged
        if(comboBoxStatistics.getSelectedIndex()==0){
            ShowTable1();
        }
        if(comboBoxStatistics.getSelectedIndex()==1){
            //ShowOccupingDevice();
            ShowTable2();
            
        }
        if(comboBoxStatistics.getSelectedIndex()==2){
            ShowTable3();
        }
    }//GEN-LAST:event_comboBoxStatisticsItemStateChanged

    public void Render(){
        for(int i=0; i< bm.getAllMembers().size();i++){
            comboBoxDepartment.addItem(bm.getAllMembers().get(i).getKhoa());
            comboBoxBranch.addItem(bm.getAllMembers().get(i).getNganh());
        }
    
    }
    
    public void ShowTable1(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("MATB");
        model.addColumn("Tên thiết bị");
        model.addColumn("Mô tả");
        for(int i=0; i< bd.getAllDevices().size();i++){
            Object[] dataRow = {bd.getAllDevices().get(i).getMaTB(), bd.getAllDevices().get(i).getTenTB(), bd.getAllDevices().get(i).getMoTaTB()};
            model.addRow(dataRow);
        }
        jTable1.setModel(model); 
    }
    
    public void ShowTable2(){ 
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("MATV");
        model.addColumn("Tên thành viên");
        model.addColumn("Khoa");
        model.addColumn("Ngành");
        model.addColumn("SDT");
        for(int i=0; i< bm.getAllMembers().size();i++){
            Object[] dataRow = {bm.getAllMembers().get(i).getMaTV(), bm.getAllMembers().get(i).getHoTen(), bm.getAllMembers().get(i).getKhoa(), bm.getAllMembers().get(i).getNganh(), bm.getAllMembers().get(i).getSdt()};
            model.addRow(dataRow);
        }
        jTable1.setModel(model);  
    }
    
    public void ShowTable3(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("MAXL");
        model.addColumn("MATV");
        model.addColumn("Hình thức");
        model.addColumn("Số tiền");
        model.addColumn("Ngày xử lý");
        model.addColumn("Trạng thái");
        for(int i=0; i< bp.getAllProcessings().size();i++){
            Object[] dataRow = {
                bp.getAllProcessings().get(i).getMaXL(), 
                bp.getAllProcessings().get(i).getMaTV().getMaTV(), 
                bp.getAllProcessings().get(i).getHinhThucXL(),
                bp.getAllProcessings().get(i).getSoTien(),
                bp.getAllProcessings().get(i).getNgayXL(),
                bp.getAllProcessings().get(i).getTrangThaiXL()         
            };
            model.addRow(dataRow);
        }
        jTable1.setModel(model);  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser borrowDateChooser;
    public javax.swing.JComboBox<String> comboBoxBranch;
    public javax.swing.JComboBox<String> comboBoxDepartment;
    public javax.swing.JComboBox<String> comboBoxStatistics;
    public javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public com.toedter.calendar.JDateChooser joinDateChooser;
    public com.toedter.calendar.JDateChooser joinTimeChooser2;
    public javax.swing.JLabel labelBorrowDate;
    public javax.swing.JLabel labelBranch;
    public javax.swing.JLabel labelDepartment;
    public javax.swing.JLabel labelJoinDate;
    public javax.swing.JLabel labelJoinTime2;
    public javax.swing.JLabel labelPayDate;
    public javax.swing.JLabel labelStatisticsFor;
    public javax.swing.JLabel labelStatus;
    public javax.swing.JLabel labelTitle;
    public com.toedter.calendar.JDateChooser payDateChooser;
    // End of variables declaration//GEN-END:variables
}
